name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff
        # Skip package installation since it requires CUDA/CuPy
        
    - name: Run Black (code formatting check)
      run: |
        black --check --diff jqc/__init__.py jqc/backend/__init__.py jqc/constants.py
        
    - name: Run Ruff (linting and import sorting) 
      run: |
        ruff check jqc/__init__.py jqc/backend/__init__.py jqc/constants.py